### ISSUE TITLE
AngularJS 참고할 부분

### ISSUE THREAD

**Issue by haruair** [haruair/note#9]
### 스타일 가이드
- https://github.com/johnpapa/angular-styleguide
- https://github.com/toddmotto/angularjs-styleguide

니폴님은 모듈만 존파파 식이고 나머지는 토드 방식을 따른다고. ng 스타일은 존파파, 토드는 구글 스타일이라고 함.
### $scope와 함수 선언

스코프 쓰면 속도가 느려져서 this를 많이 쓴다고. 익명 함수보다 일반 함수로 쓰는 이유도 속도에 기인한 모양.

```
var _this = this; // or
var vm = this;
```

this로 쓰는건 Controller As라는 문법으로 1.2 이후로 추가됨. $scope를 제외하고 컨트롤러를 작성할 수 있으며, 이 문법을 활용하면 스코프를 명확하게 명시 할 수 있는 등 장점이 많아 많이 사용되고 있다고.

관련해서 읽어볼 글은 아래:
- [Do You Like Your Angular Controllers with or without Sugar?](http://www.johnpapa.net/do-you-like-your-angular-controllers-with-or-without-sugar/)
- [A better way to $scope, angular.extend, no more “vm = this”](http://toddmotto.com/a-better-way-to-scope-angular-extend-no-more-vm-this/)

읽어보고 괜찮으면 번역하기로... 이미 있을지도?

**Comment by haruair** [comment]
- [A better way to $scope, angular.extend, no more “vm = this”](http://toddmotto.com/a-better-way-to-scope-angular-extend-no-more-vm-this/)
  - 번역 [$scope를 사용하는 더 나은 방법, angular.extend()](http://haruair.com/blog/3190)
- [Digging into Angular’s “Controller as” syntax](http://toddmotto.com/digging-into-angulars-controller-as-syntax/)
  - 번역 [Angular의 Controller As 문법 살펴보기](http://haruair.com/blog/3186)
- [Do You Like Your Angular Controllers with or without Sugar?](http://www.johnpapa.net/do-you-like-your-angular-controllers-with-or-without-sugar/)
  - 번역 [Angular 컨트롤러를 작성하는 두가지 방법](http://haruair.com/blog/3184)

짧은 글이라 저녁먹고 번역했는데 2번 글이 가장 영양가 있는 것 같다.

**Comment by haruair** [comment]
이 글이 좀 영양가 있어보인다...

- [No $scope soup, bindToController in AngularJS](http://toddmotto.com/no-scope-soup-bind-to-controller-angularjs/)

**Comment by haruair** [comment]
Todd Motto 글 번역이 많아질 것 같아 혹시나 해서 메일로 컨펌 받았음. 레퍼런스 링크 걸어준다고 완료되면 알려달라고 함. 굿굿.

**Comment by haruair** [comment]
### 스타일가이드 번역

@justinyoo 님께서 해주시기로. 헤헤. 최고임 >_<
- [todd](https://github.com/justinyoo/angularjs-styleguide)
- [johnpapa](https://github.com/justinyoo/angular-styleguide)

**Comment by justinyoo** [comment]
@haruair 헐? ㅡㅡ?

**Comment by haruair** [comment]
@justinyoo 헐 등록 안되어 있어도 멘션 가나보는군요 덜덜더더

**Comment by haruair** [comment]
어제 슬랙에서 얘기했던 Service와 Factory, Provider 차이와 용도 정리하기.

Service는 인스턴스로 생성되서 싱글턴처럼 제어 가능하고 factory는 객체로 반환하는 형태로 팩토리는 static class나 helper처럼 사용. Provider는 세세하게 아직 안봐서 잘 모르겠다. 셋 다 보고 정리.

**Comment by haruair** [comment]
[Service vs Factory - Once and for all](http://blog.thoughtram.io/angular/2015/07/07/service-vs-factory-once-and-for-all.html) 여기에 잘 정리되어 있다.
- factory는 기능을 모아둔 툴박스 느낌이고 service는 바인드된 함수를 통해 인스턴스를 생성 (`new`).
- 물론 service에서도 factory처럼 객체를 반환할 수도 있다. 이래서 더 혼란인 모양.
  - 가능하지만 지저분한 느낌? service as a factory?
  - 상황에 맞게 사용한다면 Partial Application 형태로도 사용 가능할 것 같음
- 그리고 글에서처럼 service는 (당연하게도) ES6 클래스를 사용할 수 있음

그 외 세세한 부분은 글을 참조.

**Comment by haruair** [comment]
- [No $scope soup, bindToController in AngularJS](http://toddmotto.com/no-scope-soup-bind-to-controller-angularjs/)
  - 번역 [Angular 디렉티브 때려잡기: 구조와 MVVM](http://haruair.com/blog/3198)

로직을 어떤 기준으로 분리해야 하는가에 대한 글이었는데 괜찮았음. `link`와 `controller`와의 관계라든가, `link`의 4번째 인자가 컨트롤러라는 부분이라든가.

**Comment by haruair** [comment]
- [No $scope soup, bindToController in AngularJS](http://toddmotto.com/no-scope-soup-bind-to-controller-angularjs/)
  - 번역 [$scope은 이제 그만, Angular에서 bindToController 활용하기](http://haruair.com/blog/3201)

디렉티브에서 scope를 `$scope`가 아닌 `vm`으로 받을 때 어떻게 바인딩해야 하는가에 대한 설명. `bindToController`에 객체로 지정하는건 문서에 없다는데 찾아보니 정말 true, false만 나와 있다. 디렉티브 활용에 있어 꿀팁인듯. (아니면 안티패턴?)

**Comment by haruair** [comment]
### auth 구현
- [Techniques for authentication in AngularJS applications](https://medium.com/opinionated-angularjs/techniques-for-authentication-in-angularjs-applications-7bbf0346acec) 기본적인 세션 전파, ACL 등
- [Implementing Authentication in Angular Applications](http://www.sitepoint.com/implementing-authentication-angular-applications/) sessionStorage를 이용하는데 안전한가?

다음 둘은 구현 예제인데 복잡하게 보인다. 더 단순하게는 어려운지.
- [AngularJS Basic HTTP Authentication Example](http://jasonwatmore.com/post/2014/05/26/AngularJS-Basic-HTTP-Authentication-Example.aspx)
- [AngularJS User Registration and Login Example](http://jasonwatmore.com/post/2015/03/10/AngularJS-User-Registration-and-Login-Example.aspx)

### 세션 관련
- [$cookieStore VS localStorage VS sessionStorage](http://blog.rgarom.com/cookiestore-vs-localstorage-vs-sessionstorage/) 세션을 어디에 저장할 것인가에 관해서. ngCookie를 사용할지 local or sessionStorage 사용할지. 결론은 용도에 맞게.
- [Cookies vs Tokens. Getting auth right with Angular.JS](https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/) 쿠키 방식과 토큰 방식 비교. JWT 영업글.
  - [10 Things You Should Know about Tokens](https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/) 토큰의 장점, 어떻게 다루는지, 안전한지 등에 대한 소개. `bearer` 토큰은 원래 그냥 쓸 수 있던거였나.
- [Where to Store Your JWTs - Cookies vs HTML5 Web Storage](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/)  web storage는 위험할 수 있다고 cookie를 장려함. `HttpOnly`, `Secure` 플래그를 적당히 사용하는 것을 권장. 물론 쿠키도 CSRF가 있을 수 있으니 XSRF 토큰을 JWT에 포함하는 등 방식으로 보안성을 높여야.

**Comment by haruair** [comment]
### JWT 관련
- [OAuth 2 VS JSON Web Tokens: How to secure an API](http://www.seedbox.com/en/blog/2015/06/05/oauth-2-vs-json-web-tokens-comment-securiser-un-api/) JWT를 사용하면 OAuth2와 다른건가 찾아보니 OAuth2는 보안 프레임워크인거고 JWT는 프로토콜이라고. OAuth2에 JWT를 얹어서 사용할 수도 있는 것 같음.
- [Simple AngularJS Authentication with JWT](https://thinkster.io/angularjs-jwt-auth) Angular 구현. JWT를 받아서 Interceptor를 통해 토큰을 입혀 리퀘스트를 보내는 방식.
  - 여전히 `$window.localStorage`에 토큰 보관하는데 괜찮은지 모르겠다.

인터셉터 등록은

```
// authInterceptor is a factory
app.config(($httpProvider) => { $httpProvider.interceptors.push('authInterceptor'); });
```

**Comment by haruair** [comment]
### Transclusion
- [A Guide To Transclusion in AngularJS](http://teropa.info/blog/2015/06/09/transclusion.html) Transclusion 총정리! 스코프를 오가고 막 다양한 사용 방법을 다 보여주고 있어서 엄청 위압적(?)
